### ISSUE TITLE
Development mode shows blank page

### ISSUE THREAD

**Issue by gateixeira** [IBM/transparent-supply-documentation#4]
Hi,

I'm having an issue when starting gatsby in dev mode.
`npm install` and `gatsby develop` (npm start) run just fine but I get a blank page with this error:

![image](https://user-images.githubusercontent.com/4645845/85051920-6d975100-b198-11ea-8ea2-7e18f31fb2ba.png)

Same happens under `/ift/help`. Serving a page from /public works fine.

Any ideas?

Node version v10.21.0
NPM version 6.14.4

Thank you.

**Comment by sberajaw** [comment]
Hi Gui,

You don't need to run with the older version of Node. Works fine for me with the following versions:

(LTS) Node version v12.18.1
NPM version v6.14.5

Node version v14.4.0
NPM version v6.14.5

Please try again and let us know.

Thanks!

**Comment by gateixeira** [comment]
Ok, I will have a look cause I tried first with node 14 (don't remember what minor) and got the same error, that's why I downgraded, as the node-engine in the package.json is 10. But I will give it a try. Thanks!

**Comment by gateixeira** [comment]
So, I just changed the version to match yours and got the same issue. The terminal doesn't seem to show any error though:

`~/code/farmer-connect/FC%20Docs master > node --version
v12.18.1
~/code/farmer-connect/FC%20Docs master > npm --version
6.14.5
~/code/farmer-connect/FC%20Docs master > npm install

> transparent-supply-documentation@1.0.0 postinstall /Users/gui/code/farmer-connect/FC%20Docs
> gatsby telemetry --disable

Telemetry collection disabled
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.3.1 requires a peer of react-refresh@^0.8.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

up to date in 7.968s

155 packages are looking for funding
  run `npm fund` for details

~/code/farmer-connect/FC%20Docs master > npm start                                                                                                     9s

> transparent-supply-documentation@1.0.0 start /Users/gui/code/farmer-connect/FC%20Docs
> npm run dev


> transparent-supply-documentation@1.0.0 dev /Users/gui/code/farmer-connect/FC%20Docs
> gatsby develop

success open and validate gatsby-configs - 0.067s
success load plugins - 0.842s
success onPreInit - 0.010s
success initialize cache - 0.006s
success copy gatsby files - 0.058s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.003s
success source and transform nodes - 6.522s
success building schema - 0.209s
success createPages - 0.001s
success createPagesStatefully - 1.936s
success onPreExtractQueries - 0.002s
success update schema - 0.044s
success extract queries from components - 0.194s
success write out requires - 0.036s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.105s
success onPostBootstrap - 0.285s
⠀
info bootstrap finished - 12.698s
⠀
success run queries - 0.079s - 74/74 934.98/s


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
71 pages                                                    IN_PROGRESS                                                   transparent-supply-documentation
⠀
You can now view transparent-supply-documentation in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 70.015s


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
71 pages                                                      SUCCESS                                                     transparent-supply-documentation`

**Comment by gateixeira** [comment]
The GraphQL UI is accessible.

**Comment by gateixeira** [comment]
It worked after re-cloning the repo so I'm closing the issue. Thank you @sberajaw
